inpackage: True
testonly: False
with-expecter: True
filename: "{{.InterfaceNameSnake}}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"

packages:
  github.com/bypepe77/Twitter-Clone-for-Golang/internal/infrastructure/repositories/user:
    config:
      recursive: true
      all: true
  github.com/bypepe77/Twitter-Clone-for-Golang/internal/infrastructure/jwt:
    config:
      recursive: true
      all: true